<?php

namespace GescomBundle\Repository;

/**
 * ProductSupplierRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductSupplierRepository extends \Doctrine\ORM\EntityRepository
{
}
